sudo: required
services: docker

env:
  global:
    - DIR=/tmp/docker-test

  matrix:
    - PACKAGE_URL: tests/assets/package.tar.gz
      DATABASE_URL: tests/assets/database.sql.gz

    - PACKAGE_URL: https://github.com/ambimax/developer-tools/raw/master/tests/assets/package.tar.gz
      DATABASE_URL: https://github.com/ambimax/developer-tools/raw/master/tests/assets/database.sql.gz

before_script:
  - sudo apt install --only-upgrade docker-ce -y

script:
  - >
    ./docker-deploy.sh --package-url=${PACKAGE_URL} \
      --database-url="${DATABASE_URL}" \
      --dir=${DIR} \
      --extra-package \
      --start-containers \
      --project-init="docker-compose exec nginx sh -c \"echo 'docker::init' > /var/www/htdocs/init.html\""

  - test -e ${DIR}/database.sql.gz
  - test -e ${DIR}/docker-compose.yml
  - test -e ${DIR}/extra/file.txt
  - curl localhost
  - curl localhost | grep 'docker::success'
  - curl localhost/init.html | grep 'docker::init'

after_failure:
  - ls -la
  - ls -la ${DIR}/
  - echo ${DIR}
  - echo ${PACKAGE_URL}
  - echo ${DATABASE_URL}
  - docker-compose --version
