sudo: required
services: docker

env:
  global:
    - DIR=/tmp/docker-test

  matrix:
    - PACKAGE_URL: tests/package.tar.gz
      DATABASE_URL: tests/database.sql.gz

script:
  - ./docker-deploy.sh --package-url=${PACKAGE_URL} \
    --database-url="${DATABASE_URL}" \
    --dir=${DIR} \
    --extra-package \
    --start-containers

  - test -e ${DIR}/database.tar.gz
  - test -e ${DIR}/docker-compose.yml
  - test -e ${DIR}/extras
  - curl localhost
  - curl localhost | grep 'docker::success'

after_failure:
  - ls -la
  - ls -la ${DIR}/
  - echo "Directory: ${DIR}"
  - echo "Database Url: ${DATABASE_URL}"
  - echo "Database Url: ${DATABASE_URL}"
